build:
  stage: build
  only:
    - master   
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $IMAGE_TAG
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

tag version:
  extends: build
  before_script:
    - export IMAGE_TAG=$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG/v/}
  only:
    - tags    

heroku:
  stage: deploy
  only:
    - master 
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/exoplanetia.git
    - git checkout master
    - git push heroku master